vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        joystick:
            uri_prefix: /images/joystick
            upload_destination: '%kernel.project_dir%/public/uploads/joystick'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        game:
            uri_prefix: /images/game
            upload_destination: '%kernel.project_dir%/public/uploads/game'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true